export const popularCountries = [
    'China',
    'Korea, South',
    'US',
    'Italy',
    'Indonesia'
];
/*
export const countries = [
"Afghanistan", 
"Albania", 
"Algeria", 
"Andorra", 
"Angola", 
"Antigua and Barbuda", 
"Argentina", 
"Armenia", 
"Australia", 
"Austria", 
"Azerbaijan", 
"Bahamas", 
"Bahrain", 
"Bangladesh", 
"Barbados", 
"Belarus", 
"Belgium", 
"Benin", 
"Bhutan", 
"Bolivia", 
"Bosnia and Herzegovina", 
"Brazil", 
"Brunei", 
"Bulgaria", 
"Burkina Faso", 
"Cabo Verde", 
"Cambodia", 
"Cameroon", 
"Canada", 
"Central African Republic", 
"Chad", 
"Chile", 
"China", 
"Colombia", 
"Congo (Brazzaville)", 
"Congo (Kinshasa)", 
"Costa Rica", 
"Cote d'Ivoire", 
"Croatia", 
"Diamond Princess", 
"Cuba", 
"Cyprus", 
"Czechia", 
"Denmark", 
"Djibouti", 
"Dominican Republic", 
"Ecuador", 
"Egypt", 
"El Salvador", 
"Equatorial Guinea", 
"Eritrea", 
"Estonia", 
"Eswatini", 
"Ethiopia", 
"Fiji", 
"Finland", 
"France", 
"Gabon", 
"Gambia", 
"Georgia", 
"Germany", 
"Ghana", 
"Greece", 
"Guatemala", 
"Guinea", 
"Guyana", 
"Haiti", 
"Holy See", 
"Honduras", 
"Hungary", 
"Iceland", 
"India", 
"Indonesia", 
"Iran", 
"Iraq", 
"Ireland", 
"Israel", 
"Italy", 
"Jamaica", 
"Japan", 
"Jordan", 
"Kazakhstan", 
"Kenya", 
"Korea, South", 
"Kuwait", 
"Kyrgyzstan", 
"Latvia", 
"Lebanon", 
"Liberia", 
"Liechtenstein", 
"Lithuania", 
"Luxembourg", 
"Madagascar", 
"Malaysia", 
"Maldives", 
"Malta", 
"Mauritania", 
"Mauritius", 
"Mexico", 
"Moldova", 
"Monaco", 
"Mongolia", 
"Montenegro", 
"Morocco", 
"Namibia", 
"Nepal", 
"Netherlands", 
"New Zealand", 
"Nicaragua", 
"Niger", 
"Nigeria", 
"North Macedonia", 
"Norway", 
"Oman", 
"Pakistan", 
"Panama", 
"Papua New Guinea", 
"Paraguay", 
"Peru", 
"Philippines", 
"Poland", 
"Portugal", 
"Qatar", 
"Romania", 
"Russia", 
"Rwanda", 
"Saint Lucia", 
"Saint Vincent and the Grenadines", 
"San Marino", 
"Saudi Arabia", 
"Senegal", 
"Serbia", 
"Seychelles", 
"Singapore", 
"Slovakia", 
"Slovenia", 
"Somalia", 
"South Africa", 
"Spain", 
"Sri Lanka", 
"Sudan", 
"Suriname", 
"Sweden", 
"Switzerland", 
"Taiwan*", 
"Tanzania", 
"Thailand", 
"Togo", 
"Trinidad and Tobago", 
"Tunisia", 
"Turkey", 
"Uganda", 
"Ukraine", 
"United Arab Emirates", 
"United Kingdom", 
"Uruguay", 
"US", 
"Uzbekistan", 
"Venezuela", 
"Vietnam", 
"Zambia", 
"Zimbabwe", 
"Dominica", 
"Grenada", 
"Mozambique", 
"Syria", 
"Timor-Leste", 
"Belize", 
"Laos", 
"Libya", 
"West Bank and Gaza", 
"Guinea-Bissau", 
"Mali", 
"Saint Kitts and Nevis", 
"Kosovo", 
"Burma", 
"S Zaandam"
]
*/


export const countryCodes = [
    {code: 'ae', country: 'United Arab Emirates'},
    {code: 'ar', country: 'Argentina'},
    {code: 'at', country: 'Austria'},
    {code: 'au', country: 'Australia'},
    {code: 'be', country: 'Belgium'},
    {code: 'bg', country: 'Bulgaria'},
    {code: 'br', country: 'Brazil'},
    {code: 'ca', country: 'Canada'},
    {code: 'ch', country: 'Switzerland'},
    {code: 'cn', country: 'China'},
    {code: 'co', country: 'Colombia'},
    {code: 'cu', country: 'Cuba'},
    {code: 'cz', country: 'Czechia'},
    {code: 'de', country: 'Germany'},
    {code: 'eg', country: 'Egypt'},
    {code: 'fr', country: 'France'},
    {code: 'gb', country: 'United Kingdom'},
    {code: 'gr', country: 'Greece'},
    {code: 'hu', country: 'Hungary'},
    {code: 'id', country: 'Indonesia'},
    {code: 'ie', country: 'Ireland'},
    {code: 'il', country: 'Israel'},
    {code: 'in', country: 'India'},
    {code: 'it', country: 'Italy'},
    {code: 'jp', country: 'Japan'},
    {code: 'kr', country: 'Korea, South'},
    {code: 'lt', country: 'Lithuania'},
    {code: 'lv', country: 'Latvia'},
    {code: 'ma', country: 'Morocco'},
    {code: 'mx', country: 'Mexico'},
    {code: 'my', country: 'Malaysia'},
    {code: 'ng', country: 'Nigeria'},
    {code: 'nl', country: 'Netherlands'},
    {code: 'no', country: 'Norway'},
    {code: 'nz', country: 'New Zealand'},
    {code: 'ph', country: 'Philippines'},
    {code: 'pl', country: 'Poland'},
    {code: 'pt', country: 'Portugal'},
    {code: 'ro', country: 'Romania'},
    {code: 'rs', country: 'Serbia'},
    {code: 'ru', country: 'Russia'},
    {code: 'sa', country: 'Saudi Arabia'},
    {code: 'se', country: 'Sweden'},
    {code: 'sg', country: 'Singapore'},
    {code: 'si', country: 'Slovenia'},
    {code: 'sk', country: 'Slovakia'},
    {code: 'th', country: 'Thailand'},
    {code: 'tr', country: 'Turkey'},
    {code: 'tw', country: 'Taiwan*'},
    {code: 'ua', country: 'Ukraine'},
    {code: 'us', country: 'US'},
    {code: 've', country: 'Venezuela'},
    {code: 'za', country: 'South Africa'}
]




export const countries = [
    'United Arab Emirates',
    'Argentina',
    'Austria',
    'Australia',
    'Belgium',
    'Bulgaria',
    'Brazil',
    'Canada',
    'Switzerland',
    'China',
    'Colombia',
    'Cuba',
    'Czechia',
    'Germany',
    'Egypt',
    'France',
    'United Kingdom',
    'Greece',
    'Hungary',
    'Indonesia',
    'Ireland',
    'Israel',
    'India',
    'Italy',
    'Japan',
    'Korea, South',
    'Lithuania',
    'Latvia',
    'Morocco',
    'Mexico',
    'Malaysia',
    'Nigeria',
    'Netherlands',
    'Norway',
    'New Zealand',
    'Philippines',
    'Poland',
    'Portugal',
    'Romania',
    'Serbia',
    'Russia',
    'Saudi Arabia',
    'Sweden',
    'Singapore',
    'Slovenia',
    'Slovakia',
    'Thailand',
    'Turkey',
    'Taiwan*',
    'Ukraine',
    'US',
    'Venezuela',
    'South Africa'
]